if(NOT COMMAND weld_enable_conan_support)
    function(weld_enable_conan_support)
        string(REGEX REPLACE "[-_]([a-z])" "\\1" PROJECT_NAME_SANITIZED ${PROJECT_NAME})

        foreach(dep IN LISTS ${PROJECT_NAME}_CORE_DEPS)
            list(APPEND conan_requirements "self.requires(\"${${PROJECT_NAME}_${dep}_CONAN_REF}\")")
        endforeach()
        if(DEFINED conan_requirements)
            list(JOIN conan_requirements "\n        " CONAN_REQUIREMENTS)
        else()
            set(CONAN_REQUIREMENTS "pass")
        endif()

        foreach(dep IN LISTS ${PROJECT_NAME}_EXAMPLES_DEPS)
            list(APPEND conan_examples_requirements "self.requires(\"${${PROJECT_NAME}_${dep}_CONAN_REF}\")")
        endforeach()
        if(DEFINED conan_examples_requirements)
            list(JOIN conan_examples_requirements "\n            " CONAN_EXAMPLES_REQUIREMENTS)
        else()
            set(CONAN_EXAMPLES_REQUIREMENTS "pass")
        endif()

        foreach(dep IN LISTS ${PROJECT_NAME}_TESTS_DEPS)
            list(APPEND conan_test_requirements "self.test_requires(\"${${PROJECT_NAME}_${dep}_CONAN_REF}\")")
        endforeach()
        if(DEFINED conan_test_requirements)
            list(JOIN conan_test_requirements "\n        " CONAN_TEST_REQUIREMENTS)
        else()
            set(CONAN_TEST_REQUIREMENTS "pass")
        endif()

        foreach(type LIBRARIES EXECUTABLES)
            foreach(target IN LISTS ${PROJECT_NAME}_${type})
                set(name ${${PROJECT_NAME}_${target}_NAME})
                list(APPEND conan_components "self.cpp_info.components[\"${name}\"].set_property(\"cmake_target_name\", \"${PROJECT_NAME}::${name}\")")

                if(type STREQUAL LIBRARIES)
                    list(APPEND conan_components "self.cpp_info.components[\"${name}\"].libs = [\"${target}\"]")
                else()
                    list(APPEND conan_components "self.cpp_info.components[\"${name}\"].exe = [\"${target}\"]")
                    list(APPEND conan_components "self.cpp_info.components[\"${name}\"].bindirs = [\"${CMAKE_INSTALL_BINDIR}\"]")
                endif()

                list(JOIN ${PROJECT_NAME}_${target}_DEPS "\", \"" target_deps)
                list(APPEND conan_components "self.cpp_info.components[\"${name}\"].requires = [\"${target_deps}\"]")
            endforeach()
            list(JOIN conan_components "\n        " CONAN_COMPONENTS)
        endforeach()

        if(DEFINED ${PROJECT_NAME}_LIBRARIES AND NOT DEFINED ${PROJECT_NAME}_EXECUTABLES)
            set(CONAN_PACKAGE_TYPE "library")
        elseif(NOT DEFINED ${PROJECT_NAME}_LIBRARIES AND DEFINED ${PROJECT_NAME}_EXECUTABLES)
            set(CONAN_PACKAGE_TYPE "application")
        else()
            set(CONAN_PACKAGE_TYPE "unknown")
        endif()

        configure_file(${WELD_API_DIR}/templates/conanfile.py ${CMAKE_CURRENT_SOURCE_DIR}/conanfile.py)
    endfunction()
endif()