 if(NOT COMMAND weld_parse_dep_file)
    function(weld_parse_dep_file)
        file(READ ${CMAKE_CURRENT_SOURCE_DIR}/deps.json deps)
        foreach(category core tests examples optional)
            string(JSON type TYPE ${deps} ${category})
            string(JSON length LENGTH ${deps} ${category})
            math(EXPR max_index "${length}-1")
            foreach(index RANGE ${max_index})
                string(JSON dep MEMBER ${deps} ${category} ${index})
                string(JSON dep_version ERROR_VARIABLE error GET ${deps} ${category} ${dep} "version")
                if(NOT dep_version)
                    message(FATAL_ERROR "[weld] Dependency ${dep} has no version specified. Please provide a 'version' field.")
                endif()

                list(APPEND ${PROJECT_NAME}_ALL_DEPS ${dep})
                set(${PROJECT_NAME}_ALL_DEPS ${${PROJECT_NAME}_ALL_DEPS} PARENT_SCOPE)

                set(${PROJECT_NAME}_${dep}_VERSION ${dep_version} PARENT_SCOPE)

                string(TOUPPER ${category} category_var)
                list(APPEND ${PROJECT_NAME}_${category_var}_DEPS ${dep})
                set(${PROJECT_NAME}_${category_var}_DEPS ${${PROJECT_NAME}_${category_var}_DEPS} PARENT_SCOPE)

                string(JSON dep_find_name ERROR_VARIABLE error GET ${deps} ${category} ${dep} "find_name")
                if(dep_find_name)
                    set(${PROJECT_NAME}_${dep}_FIND_NAME ${dep_find_name} PARENT_SCOPE)
                else()
                    set(${PROJECT_NAME}_${dep}_FIND_NAME ${dep} PARENT_SCOPE)
                endif()

                string(JSON dep_fallback ERROR_VARIABLE error GET ${deps} ${category} ${dep} "fallback")
                if(dep_fallback)
                    set(${PROJECT_NAME}_${dep}_FALLBACK ${dep_fallback} PARENT_SCOPE)
                endif()

                string(JSON dep_conan_ref ERROR_VARIABLE error GET ${deps} ${category} ${dep} "conan_ref")
                if(dep_conan_ref)
                    if(dep_conan_ref MATCHES "^[^/]+/.+$")
                        # version specified in ref, use as is
                        set(${PROJECT_NAME}_${dep}_CONAN_REF ${dep_conan_ref} PARENT_SCOPE)
                    else()
                        # no version specified, add it
                        set(${PROJECT_NAME}_${dep}_CONAN_REF "${dep_conan_ref}/${dep_version}" PARENT_SCOPE)
                    endif()
                else()
                    set(${PROJECT_NAME}_${dep}_CONAN_REF "${dep}/${dep_version}" PARENT_SCOPE)
                endif()

                string(JSON dep_vcpkg_port ERROR_VARIABLE error GET ${deps} ${category} ${dep} "vcpkg_port")
                if(dep_vcpkg_port)
                    set(${PROJECT_NAME}_${dep}_VCPKG_PORT ${dep_vcpkg_port} PARENT_SCOPE)
                else()
                    set(${PROJECT_NAME}_${dep}_VCPKG_PORT ${dep} PARENT_SCOPE)
                endif()
            endforeach()
        endforeach()
    endfunction()
endif()